### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by ccarnero** [fsprojects/atom-fsharp#109]
[Enter steps to reproduce below:]

1. Try to send .fsx file to FSI

**Atom Version**: 1.0.5
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/christian/.atom/packages/atom-fsharp/lib/fsharp.js:1963

TypeError: Cannot read property 'getPath' of undefined
    at Interactive__sendToFsi$ (/Users/christian/.atom/packages/atom-fsharp/lib/fsharp.js:1963:36)
    at Interactive__sendLine$ (/Users/christian/.atom/packages/atom-fsharp/lib/fsharp.js:1941:5)
    at atom-text-editor.<anonymous> (/Users/christian/.atom/packages/atom-fsharp/lib/fsharp.js:1813:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -1:22 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:18.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:18 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:18 FAKE:Show-Builds (atom-text-editor.editor)
     -1:15.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:14.1.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -1:12 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:09.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:09.8.0 FAKE:Build-Default (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:20.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -0:15.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:10.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:06.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 FSI:Send-Line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.10.0
atom-yeoman, v0.3.11
json-schema, v0.1.11
language-csharp, v0.7.0
linter, v1.3.4
omnisharp-atom, v0.23.1

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.11.3`
