### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/Users/david/build/design.xamarin.com/s...

### ISSUE THREAD

**Issue by dvdsgl** [fsprojects/atom-fsharp#112]
1. Open any file (in my case, I wasn't event using fsharp)
2. Delete or move the file with the tab still open
3. Try to close (possibly even access) the corresponding tab

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.12.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/david/build/design.xamarin.com/src/Text'

```
At ATOM_SHELL_ASAR.js:50

Error: ENOENT: no such file or directory, lstat '/Users/david/build/design.xamarin.com/src/Text'
  at Error (native)
  at fs.lstatSync (fs.js:836:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at findFsProj (/Users/david/.atom/packages/atom-fsharp/lib/fsharp.js:3436:18)
  at Parser__parseProjectForEditor$ (/Users/david/.atom/packages/atom-fsharp/lib/fsharp.js:3484:13)
  at /Users/david/.atom/packages/atom-fsharp/lib/fsharp.js:3405:7
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:320:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:242:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:306:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:300:19)
  at Pane.module.exports.Pane.activatePreviousItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:271:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:388:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:458:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:435:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:617:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:656:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-element.js:290:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "language-javascript-jsx",
      "omnisharp-atom"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-fsharp, v0.12.0
atom-yeoman, v0.3.12
jshint, v1.3.10
json-schema, v0.1.11
language-csharp, v0.7.0
language-cshtml, v0.1.1
language-ejs, v0.2.0
language-fsharp, v0.8.4
language-haskell, v1.3.1
language-purescript, v0.4.0
language-sln, v0.1.0
language-swift, v0.4.0
linter, v1.4.2
linter-coffeelint, v1.0.2
pretty-json, v0.4.1
react, v0.12.6
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in `0.12.1`
