### ISSUE TITLE
Failed to load the atom-fsharp package

### ISSUE THREAD

**Issue by koenmetsu** [fsprojects/atom-fsharp#85]
NB: I am working behind a proxy, proxy is set in apm file. Probably related.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.6.2

### Stack Trace

Failed to load the atom-fsharp package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\exi342\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\exi342\.atom\packages\atom-fsharp-0.6.2\lib\fsharp.js:3:12)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\exi342\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Looks like some modules haven't installed. 

Go to `C:\Users\USERNAME\.atom\packages\atom-fsharp` and run `npm install`

**Comment by koenmetsu** [comment]
Seems to have solved itself somehow.
