### ISSUE TITLE
Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

### ISSUE THREAD

**Issue by rodrigovidal** [fsprojects/atom-fsharp#94]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Windows 8.1
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'markBufferRange' of undefined

```
At C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:1660

TypeError: Cannot read property 'markBufferRange' of undefined
    at action (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:1660:27)
    at Array__Iterate$SymbolUse_SymbolUse_ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:162:16)
    at Array__Fold$SymbolUse__Unit_SymbolUse__Unit_ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:78:24)
    at Array__FoldIndexed$Unit__SymbolUse_Unit__SymbolUse_ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:118:22)
    at Array__Fold$SymbolUse__Unit_SymbolUse__Unit_ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:72:12)
    at Array__Iterate$SymbolUse_SymbolUse_ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:158:12)
    at HighlightUse__showHighlight$ (C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:1674:5)
    at C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:1567:14
    at Emitter.module.exports.Emitter.emit (C:\Users\Rodrigo\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\Rodrigo\.atom\packages\atom-fsharp\lib\fsharp.js:925:31
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-fsharp, v0.8.0
FSharp, vundefined
language-fsharp, v0.8.4

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 0.8.2
