### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\Shai\Documents\Visual Studio 2013\Pro...

### ISSUE THREAD

**Issue by smatsri** [fsprojects/atom-fsharp#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.8.0

### Stack Trace

Uncaught Error: ENOTDIR: not a directory, scandir 'C:\Users\Shai\Documents\Visual Studio 2013\Projects\Type-Driven Development with FSharp\1. Feedback from Types\Polling Consumer.fsx'

```
At C:\Users\Shai\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\q\q.js:128

Error: ENOTDIR: not a directory, scandir 'C:\Users\Shai\Documents\Visual Studio 2013\Projects\Type-Driven Development with FSharp\1. Feedback from Types\Polling Consumer.fsx'
    at Error (native)
    at Object.fs.readdirSync (fs.js:805:18)
    at Object.fs.readdirSync (ATOM_SHELL_ASAR.js:441:28)
    at findFsProj (C:\Users\Shai\.atom\packages\atom-fsharp\lib\fsharp.js:2968:25)
    at Parser__parseProjectForEditor$ (C:\Users\Shai\.atom\packages\atom-fsharp\lib\fsharp.js:3009:13)
    at C:\Users\Shai\.atom\packages\atom-fsharp\lib\fsharp.js:2923:7
    at Emitter.module.exports.Emitter.emit (C:\Users\Shai\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at C:\Users\Shai\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane-container.js:343:34
    at Emitter.module.exports.Emitter.emit (C:\Users\Shai\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Shai\AppData\Local\atom\app-1.0.2\resources\app.asar\src\pane.js:238:22)
```

### Commands

```
     -1:56.8.0 fsharp:autocomplete (atom-text-editor.editor.is-focused)
     -1:56.8.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:45.2.0 fsharp:autocomplete (atom-text-editor.editor.is-focused)
     -1:45.2.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:43.1.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:57.7.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:56.9.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:37.8.0 grammar-selector:show (atom-text-editor.editor)
     -0:36 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:36 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:28.2.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:05.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:03.7.0 linter:set-bubble-transparent (atom-text-editor.editor.is-focused)
     -0:03.4.0 FSI:Send-Selection (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-fsharp, v0.8.0
atom-typescript, v5.0.29
language-fsharp, v0.8.4
linter, v1.2.4
node-debugger, vundefined

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed in 0.8.2
